[build]
builder = "nixpacks"

[build.nixpacksConfigPath]
configPath = "./nixpacks.toml"

[deploy]
startCommand = "/opt/venv/bin/python manage.py migrate && /opt/venv/bin/python manage.py runserver 0.0.0.0:$PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10