[build]
builder = "nixpacks"

[deploy]
startCommand = "bash -c \"echo '=== CREATING TEST DATA: '\\$(date)' ===' && python manage.py migrate --noinput && python manage.py create_test_data && echo '=== TEST DATA CREATION COMPLETE: '\\$(date)' ===' && sleep 300\""
# healthcheckPath = "/"  # Temporarily disabled for debugging
# healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 15

[deploy.envs]
PYTHON_VERSION = "3.11"
