[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn back.wsgi --bind 0.0.0.0:$PORT"
# healthcheckPath = "/"  # Temporarily disabled for debugging
# healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 15

[deploy.envs]
PYTHON_VERSION = "3.11"
