[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn back.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/api/v1/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.envs]
PYTHON_VERSION = "3.11"
