[build]
builder = "nixpacks"

[deploy]
startCommand = "bash -c \"echo '=== CONTAINER START: '\\$(date)' ===' && echo 'Python version:' && python --version && echo '=== RUNNING MIGRATIONS: '\\$(date)' ===' && python manage.py migrate --noinput && echo '=== CREATING TEST DATA: '\\$(date)' ===' && python manage.py create_test_data --users 15 --companies 8 && echo '=== TESTING DJANGO: '\\$(date)' ===' && python -c 'import django; django.setup(); print(\\\"Django OK - Version:\\\", django.get_version())' && echo '=== TESTING WSGI: '\\$(date)' ===' && python -c 'from back.wsgi import application; print(\\\"WSGI OK\\\")' && echo '=== STARTING GUNICORN: '\\$(date)' ===' && echo 'PORT='\\${PORT:-8000} && echo 'Starting Gunicorn server...' && gunicorn back.wsgi:application --bind 0.0.0.0:\\${PORT:-8000} --workers 1 --timeout 120 --log-level info --access-logfile - --error-logfile - --preload\""
# healthcheckPath = "/"  # Temporarily disabled for debugging
# healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 15

[deploy.envs]
PYTHON_VERSION = "3.11"
