# Generated by Django 5.0.6 on 2025-08-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_company_description_user_employee_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
