# Generated by Django 5.0.6 on 2025-08-30 16:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resume_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('capital', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('company_url', models.URLField(blank=True, max_length=500)),
                ('campaign_code', models.CharField(blank=True, max_length=50)),
                ('employee_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('founded_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)])),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100)),
                ('company_description', models.TextField(blank=True)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_department', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'company_profiles',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=200)),
                ('education_type', models.CharField(choices=[('high_school', '高等学校'), ('vocational', '専門学校'), ('junior_college', '短期大学'), ('university', '大学'), ('graduate', '大学院'), ('other', 'その他')], max_length=50)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.resume')),
            ],
            options={
                'db_table': 'educations',
                'ordering': ['order', '-graduation_date'],
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('obtained_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=100)),
                ('credential_url', models.URLField(blank=True, max_length=500)),
                ('order', models.IntegerField(default=0)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.resume')),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['order', '-obtained_date'],
            },
        ),


    ]
