# Generated by Django 5.0.6 on 2025-08-28 08:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_resume_extra_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('issuer', models.CharField(blank=True, max_length=200)),
                ('obtained_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['order', '-obtained_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('capital', models.BigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('company_url', models.URLField(blank=True, max_length=500)),
                ('campaign_code', models.CharField(blank=True, max_length=50)),
                ('employee_count', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('founded_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800)])),
                ('industry', models.CharField(blank=True, db_index=True, max_length=100)),
                ('company_description', models.TextField(blank=True)),
                ('headquarters', models.CharField(blank=True, max_length=200)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('contact_department', models.CharField(blank=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'company_profiles',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('school_name', models.CharField(max_length=200)),
                ('faculty', models.CharField(blank=True, max_length=100)),
                ('major', models.CharField(blank=True, max_length=100)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('education_type', models.CharField(choices=[('high_school', '高等学校'), ('vocational', '専門学校'), ('junior_college', '短期大学'), ('university', '大学'), ('graduate', '大学院'), ('other', 'その他')], max_length=20)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'educations',
                'ordering': ['order', '-graduation_date'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='application',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies_used',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='title',
            field=models.CharField(default='履歴書', max_length=200),
        ),
        # Skip ID field alteration - will be handled by recreation
        # migrations.AlterField(
        #     model_name='application',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='application',
            name='match_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.resume'),
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', '未確認'), ('viewed', '確認済み'), ('accepted', '選考中'), ('interview', '面接中'), ('offered', '内定'), ('rejected', '不採用'), ('hired', '採用'), ('withdrawn', '辞退')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='experience',
            name='employment_type',
            field=models.CharField(choices=[('fulltime', '正社員'), ('contract', '契約社員'), ('parttime', 'パート・アルバイト'), ('dispatch', '派遣'), ('freelance', 'フリーランス'), ('internship', 'インターンシップ'), ('other', 'その他')], max_length=20),
        ),
        # Skip ID field alteration - will be handled by recreation
        # migrations.AlterField(
        #     model_name='experience',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='experience',
            name='industry',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        # Skip ID field alteration - will be handled by recreation
        # migrations.AlterField(
        #     model_name='resume',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='resume',
            name='match_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='seekerprofile',
            name='experience_years',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)]),
        ),
        # Skip ID field alteration - will be handled by recreation
        # migrations.AlterField(
        #     model_name='seekerprofile',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['-match_score'], name='application_match_s_48d9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['resume', 'order'], name='experiences_resume__80007b_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['industry'], name='experiences_industr_8e8348_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['employment_type'], name='experiences_employm_c02bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='experience',
            index=models.Index(fields=['period_from', 'period_to'], name='experiences_period__7982ec_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['user', 'is_active'], name='resumes_user_id_544e1f_idx'),
        ),
        migrations.AddIndex(
            model_name='resume',
            index=models.Index(fields=['-match_score'], name='resumes_match_s_e0aeca_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['prefecture'], name='seeker_prof_prefect_8102c8_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['experience_years'], name='seeker_prof_experie_20ab8f_idx'),
        ),
        migrations.AddIndex(
            model_name='seekerprofile',
            index=models.Index(fields=['graduation_year'], name='seeker_prof_graduat_0c9778_idx'),
        ),
        migrations.AddField(
            model_name='certification',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='core.resume'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='education',
            name='resume',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='educations', to='core.resume'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['company_name'], name='company_pro_company_43f4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['industry'], name='company_pro_industr_dbd29a_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['employee_count'], name='company_pro_employe_0d2737_idx'),
        ),
        migrations.AddIndex(
            model_name='companyprofile',
            index=models.Index(fields=['founded_year'], name='company_pro_founded_f7351a_idx'),
        ),
    ]
