# Generated by Django 5.0.6 on 2025-08-30 16:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_user_profile_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrivacySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_profile_public', models.BooleanField(default=False, help_text='プロフィールを公開するか')),
                ('show_email', models.BooleanField(default=False, help_text='メールアドレスを公開するか')),
                ('show_phone', models.BooleanField(default=False, help_text='電話番号を公開するか')),
                ('show_resumes', models.BooleanField(default=True, help_text='履歴書を公開するか')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プライバシー設定',
                'verbose_name_plural': 'プライバシー設定',
                'db_table': 'user_privacy_settings',
            },
        ),
        migrations.CreateModel(
            name='UserProfileExtension',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_image_url', models.URLField(blank=True, help_text='プロフィール画像URL', max_length=500)),
                ('bio', models.TextField(blank=True, help_text='自己紹介')),
                ('headline', models.CharField(blank=True, help_text='キャッチフレーズ', max_length=200)),
                ('location', models.CharField(blank=True, help_text='居住地', max_length=100)),
                ('website_url', models.URLField(blank=True, max_length=500)),
                ('github_url', models.URLField(blank=True, max_length=500)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('available_for_work', models.BooleanField(default=True, help_text='仕事を探しているか')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_extension', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'プロフィール拡張',
                'verbose_name_plural': 'プロフィール拡張',
                'db_table': 'user_profile_extensions',
            },
        ),
    ]
